"""Skill name alias mapping for deduplication.

Generated from skill_alias_mapping.csv. Maps variant names to canonical forms.
"""

from __future__ import annotations


# {alias: canonical_name} — case-sensitive lookup first, then case-insensitive
SKILL_ALIASES: dict[str, str] = {
    "Artificial Intelligence (AI)": "Artificial Intelligence",
    "generative AI": "Generative AI",
    "Large Language Model": "Large Language Models",
    "Large Language Models (LLM)": "Large Language Models",
    "Large Language Models (LLMs)": "Large Language Models",
    "Large Language Model (LLM)": "Large Language Models",
    "large language models": "Large Language Models",
    "computer vision": "Computer Vision",
    "Natural Language Processing (NLP)": "Natural Language Processing",
    "Unsupervised learning": "Unsupervised Learning",
    "Retrieval Augmented Generation": "Retrieval-Augmented Generation",
    "Retrieval-Augmented Generation (RAG)": "Retrieval-Augmented Generation",
    "Retrieval Augmented Generation (RAG)": "Retrieval-Augmented Generation",
    "Retrieval-augmented generation": "Retrieval-Augmented Generation",
    "Supervised learning": "Supervised Learning",
    "Time-Series Forecasting": "Time Series Forecasting",
    "Multi-Agent Systems": "Multi-agent Systems",
    "OLLAMA": "Ollama",
    "Few-Shot Learning": "Few-shot Learning",
    "Self-Supervised Learning": "Self-supervised Learning",
    "Semi-Supervised Learning": "Semi-supervised Learning",
    "Multimodal Learning": "Multimodal AI",
    "Feature extraction": "Feature Extraction",
    "Llama": "LLaMa",
    "LLaMA": "LLaMa",
    "Model Fine-tuning": "Model Fine-Tuning",
    "Online Learning": "Online learning",
    "Tensorflow": "TensorFlow",
    "Scikit-learn": "scikit-learn",
    "Scikit-Learn": "scikit-learn",
    "Langchain": "LangChain",
    "langchain": "LangChain",
    "HuggingFace": "Hugging Face",
    "Jax": "JAX",
    "langgraph": "LangGraph",
    "llamaindex": "LlamaIndex",
    "Model Context Protocol": "MCP",
    "Model Context Protocol (MCP)": "MCP",
    "HuggingFace Transformers": "Hugging Face Transformers",
    "Compute Graph Optimization": "Compute graph optimization",
    "REST API": "REST",
    "RESTful API": "REST",
    "RESTful APIs": "REST",
    "REST APIs": "REST",
    "RESTful": "REST",
    "Websockets": "WebSockets",
    "Socket programming": "Socket Programming",
    "Ajax": "AJAX",
    "Server Sent Events": "Server-Sent Events",
    "NodeJS": "Node.js",
    "SpringBoot": "Spring Boot",
    "Rails": "Ruby on Rails",
    "Express": "Express.js",
    "WildFly": "Wildfly",
    "GlassFish": "Glassfish",
    "Amazon Web Services": "AWS",
    "Continuous Integration/Continuous Deployment": "CI/CD",
    "Continuous Integration/Continuous Delivery": "CI/CD",
    "CICD": "CI/CD",
    "Microsoft Azure": "Azure",
    "Google Cloud Platform": "GCP",
    "Google Cloud": "GCP",
    "Google Cloud Platform (GCP)": "GCP",
    "Cloud computing": "Cloud Computing",
    "IaC": "Infrastructure as Code",
    "Infrastructure-as-code": "Infrastructure as Code",
    "Infrastructure-as-Code": "Infrastructure as Code",
    "AWS DynamoDB": "DynamoDB",
    "Red Hat OpenShift": "OpenShift",
    "Argo CD": "ArgoCD",
    "Cloud-Native": "Cloud Native",
    "Cloud-native": "Cloud Native",
    "Cloud infrastructure": "Cloud Infrastructure",
    "GPU programming": "GPU Programming",
    "High-Performance Computing (HPC)": "High-Performance Computing",
    "AWS Sagemaker": "AWS SageMaker",
    "KubeFlow": "Kubeflow",
    "Point cloud processing": "Point Cloud Processing",
    "Azure Cosmos DB": "Cosmos DB",
    "MinIO": "Minio",
    "Route 53": "Route53",
    "data structures": "Data Structures",
    "algorithms": "Algorithms",
    "Multi-threading": "Multithreading",
    "Algorithm design": "Algorithm Design",
    "Linear algebra": "Linear Algebra",
    "Linear programming": "Linear Programming",
    "Nonlinear optimization": "Nonlinear Optimization",
    "Control theory": "Control Theory",
    "Mathematical modeling": "Mathematical Modeling",
    "Memory management": "Memory Management",
    "PowerBI": "Power BI",
    "Microsoft Power BI": "Power BI",
    "Microsoft PowerBI": "Power BI",
    "MS Power BI": "Power BI",
    "Data analysis": "Data Analysis",
    "Apache Kafka": "Kafka",
    "Numpy": "NumPy",
    "numpy": "NumPy",
    "pandas": "Pandas",
    "Apache Spark": "Spark",
    "matplotlib": "Matplotlib",
    "Airflow": "Apache Airflow",
    "DBT": "dbt",
    "plotly": "Plotly",
    "Jupyter Notebooks": "Jupyter Notebook",
    "seaborn": "Seaborn",
    "Time-series analysis": "Time Series Analysis",
    "Data Flow": "Dataflow",
    "Apache Nifi": "Apache NiFi",
    "Site Catalyst": "SiteCatalyst",
    "StatsModels": "statsmodels",
    "Microsoft SQL Server": "SQL Server",
    "MS SQL Server": "SQL Server",
    "ElasticSearch": "Elasticsearch",
    "EntityFramework": "Entity Framework",
    "Prisma ORM": "Prisma",
    "MSSQL": "MS SQL",
    "database fundamentals": "Database Fundamentals",
    "Database systems": "Database Systems",
    "nHibernate": "NHibernate",
    "Non-relational Databases": "Non-Relational Databases",
    "Non-relational databases": "Non-Relational Databases",
    "UI/UX design": "UI/UX Design",
    "UX design": "UX Design",
    "UX": "User Experience",
    "User Experience (UX)": "User Experience",
    "FigJam": "Figjam",
    "Human Computer Interaction": "Human-Computer Interaction",
    "3D graphics": "3D Graphics",
    "3D modeling": "3D Modeling",
    "3D Programming": "3D programming",
    "3DSMax": "3ds Max",
    "ReactJS": "React",
    "React.js": "React",
    "AngularJS": "Angular",
    "Vue": "Vue.js",
    "NextJS": "Next.js",
    "JQuery": "jQuery",
    "TailwindCSS": "Tailwind CSS",
    "Sass": "SASS",
    "SvelteKit": "Svelte",
    "LESS": "Less",
    "Material UI": "Material-UI",
    "RadixUI": "Radix UI",
    "Cross-Browser Compatibility": "Cross-browser compatibility",
    "NGRX": "NgRx",
    "TanStack": "Tanstack",
    "Cross-browser Development": "Cross-Browser Development",
    "Micro-frontend": "Micro Frontend",
    "Ext JS": "ExtJs",
    "SolidJS": "Solid.js",
    "styled-components": "Styled-components",
    "JIRA": "Jira",
    "QA": "Quality Assurance",
    "Quality Assurance (QA)": "Quality Assurance",
    "OpenAI API": "OpenAI",
    "LUA": "Lua",
    "transformers": "Transformers",
    "Co-Pilot": "Copilot",
    "CoPilot": "Copilot",
    "End-to-end Testing": "End-to-End Testing",
    "IP networking": "IP Networking",
    "Object detection": "Object Detection",
    "Apache Hive": "Hive",
    "MuJoCo": "Mujoco",
    "UI Path": "UiPath",
    "UIPath": "UiPath",
    "Cross-Browser Testing": "Cross Browser Testing",
    "Fortran": "FORTRAN",
    "Open API": "OpenAPI",
    "Testing frameworks": "Testing Frameworks",
    "UserTesting": "User Testing",
    "Multi-Factor Authentication": "Multifactor Authentication",
    "Resource Scheduling": "Resource scheduling",
    "WebDriver": "Webdriver",
    "ERD": "Entity Relationship Diagram (ERD)",
    "Jobs To Be Done (JTBD)": "JTBD",
    "IOT": "IoT",
    "Arm": "ARM",
    "Signal processing": "Signal Processing",
    "DSP": "Digital Signal Processing",
    "Digital Signal Processing (DSP)": "Digital Signal Processing",
    "System Verilog": "SystemVerilog",
    "Real-time systems": "Real-time Systems",
    "Real-Time Systems": "Real-time Systems",
    "LabView": "LabVIEW",
    "Real-Time Operating System": "Real-time Operating System",
    "ASIC design": "ASIC Design",
    "CAN Bus": "CAN bus",
    "CANbus": "CAN bus",
    "Sensor fusion": "Sensor Fusion",
    "CANape": "CANApe",
    "Real-time programming": "Real-time Programming",
    "Hardware-Software Integration": "Hardware/Software Integration",
    "LIDAR": "LiDAR",
    "MODBUS": "Modbus",
    "RS422": "RS-422",
    "State Estimation": "State estimation",
    "Hardware-Software Co-Design": "Hardware-Software Co-design",
    "OPC-UA": "OPC UA",
    "RS-232": "RS232",
    "Real-time processing": "Real-time Processing",
    "SCRUM": "Scrum",
    "Microservices Architecture": "Microservices",
    "Microservice Architecture": "Microservices",
    "Object-oriented programming": "Object-Oriented Programming",
    "Object Oriented Programming": "Object-Oriented Programming",
    "Object-Oriented Programming (OOP)": "Object-Oriented Programming",
    "Object-oriented Programming": "Object-Oriented Programming",
    "Object-oriented design": "Object-Oriented Design",
    "Software Development Lifecycle": "Software Development Life Cycle",
    "Software Development Life Cycle (SDLC)": "Software Development Life Cycle",
    "Apache Hadoop": "Hadoop",
    "Design patterns": "Design Patterns",
    "Unified Modeling Language": "UML",
    "Unified Modeling Language (UML)": "UML",
    "Functional programming": "Functional Programming",
    "functional programming": "Functional Programming",
    "Software design patterns": "Software Design Patterns",
    "SOA": "Service-Oriented Architecture",
    "Service-oriented architecture": "Service-Oriented Architecture",
    "Agile methodology": "Agile Methodology",
    "Back-end Development": "Backend Development",
    "Frontend Development": "Front-end Development",
    "Client/Server Architecture": "Client-Server Architecture",
    "Event-driven architecture": "Event-Driven Architecture",
    "Event-driven Architecture": "Event-Driven Architecture",
    "Multi-threaded Programming": "Multithreaded Programming",
    "Multi-threaded programming": "Multithreaded Programming",
    "Multithreaded programming": "Multithreaded Programming",
    "Software development best practices": "Software Development Best Practices",
    "HIL": "Hardware-in-the-Loop (HIL)",
    "Hardware-in-the-Loop": "Hardware-in-the-Loop (HIL)",
    "Agile Methodologies": "Agile methodologies",
    "Full Stack Development": "Full-stack Development",
    "Object-oriented analysis and design": "Object-Oriented Analysis and Design",
    "Object-oriented development": "Object-Oriented Development",
    "Software-in-the-Loop (SIL)": "SIL",
    "Software-in-the-Loop": "SIL",
    "Model-Driven Development": "Model-driven development",
    "Excel": "Microsoft Excel",
    "MS Excel": "Microsoft Excel",
    "Word": "Microsoft Word",
    "PowerPoint": "Microsoft PowerPoint",
    "MS PowerPoint": "Microsoft PowerPoint",
    "Outlook": "Microsoft Outlook",
    "Microsoft SharePoint": "SharePoint",
    "MS Teams": "Microsoft Teams",
    "Microsoft Visual Studio": "Visual Studio",
    "Access": "Microsoft Access",
    "PowerApps": "Power Apps",
    "Visual Studio Code": "VS Code",
    "VSCode": "VS Code",
    "PowerQuery": "Power Query",
    "Microsoft PowerApps": "Microsoft Power Apps",
    "iOS Development": "iOS",
    "IOS": "iOS",
    "DataDog": "Datadog",
    "ELK Stack": "Elastic Stack",
    "Yang": "YANG",
    "WiFi": "Wi-Fi",
    "ISIS": "IS-IS",
    "OSI model": "OSI Model",
    "Netconf": "NETCONF",
    "Software Defined Networking": "SDN",
    "Software-Defined Networking": "SDN",
    "Software-Defined Networking (SDN)": "SDN",
    "dpdk": "DPDK",
    "RAN": "Radio Access Network (RAN)",
    "Typescript": "TypeScript",
    "Golang": "Go",
    "GoLang": "Go",
    "NET": ".NET",
    "SWIFT": "Swift",
    "Tcl": "TCL",
    "NET Core": ".NET Core",
    "Matlab": "MATLAB",
    "Risk assessment": "Risk Assessment",
    "STATA": "Stata",
    "RedCap": "REDCap",
    "Good Manufacturing Practices": "GMP",
    "Good Manufacturing Practices (GMP)": "GMP",
    "IFRS 17": "IFRS17",
    "Mixed Effects Models": "Mixed-Effects Models",
    "Pathwise": "PathWise",
    "Statistical analysis software": "Statistical Analysis Software",
    "Statistical Process Control": "Statistical Process Control (SPC)",
    "BASH": "Bash",
    "bash": "Bash",
    "UNIX": "Unix",
    "Powershell": "PowerShell",
    "Shell scripting": "Shell Scripting",
    "shell scripting": "Shell Scripting",
    "Command-line Interface": "Command Line Interface",
    "Command-line interface": "Command Line Interface",
    "Linux Command Line": "Linux command line",
    "Unix shell": "Unix Shell",
    "Cyber Security": "Cybersecurity",
    "Incident response": "Incident Response",
    "WebAuthn": "WebAuthN",
    "Vulnerability scanning": "Vulnerability Scanning",
    "OAuth2.0": "OAuth 2.0",
    "Anti-Virus": "Antivirus",
    "HashiCorp Vault": "Hashicorp Vault",
    "Unit testing": "Unit Testing",
    "Selenium WebDriver": "Selenium",
    "Test automation": "Test Automation",
    "Automated testing": "Automated Testing",
    "Junit": "JUnit",
    "Test Driven Development": "Test-Driven Development",
    "Test-driven development": "Test-Driven Development",
    "Test-driven Development": "Test-Driven Development",
    "Test-Driven Development (TDD)": "Test-Driven Development",
    "Pytest": "pytest",
    "PyTest": "pytest",
    "GoogleTest": "Google Test",
    "xUnit": "XUnit",
    "Black-box Testing": "Black Box Testing",
    "Black box testing": "Black Box Testing",
    "SOAPUI": "SoapUI",
    "SOAP UI": "SoapUI",
    "White box testing": "White Box Testing",
    "White-box Testing": "White Box Testing",
    "Behavior-driven Development": "Behavior Driven Development",
    "Behavior-Driven Development": "Behavior Driven Development",
    "RestAssured": "Rest Assured",
    "REST Assured": "Rest Assured",
    "Acceptance Test-Driven Development": "Acceptance Test Driven Development",
    "Code review": "Code Review",
    "MacOS": "macOS",
    "SAP ERP": "SAP",
    "gdb": "GDB",
    "XCode": "Xcode",
    "Mulesoft": "MuleSoft",
    "NPM": "npm",
    "Technical documentation": "Technical Documentation",
    "VMWare": "VMware",
    "pnpm": "PNPM",
    "Code generation": "Code Generation",
    "MAC": "Mac",
    "Zookeeper": "ZooKeeper",
    "Cal.com": "cal.com",
    "Datasheets": "Data Sheets",
    "Esri": "ESRI",
    "FFmpeg": "FFMPEG",
    "G Suite": "G-Suite",
    "PyAutoGUI": "Pyautogui",
    "GIT": "Git",
    "git": "Git",
    "BitBucket": "Bitbucket",
    "Version control": "Version Control",
    "Version control systems": "Version Control Systems",
    "Plastic SCM": "PlasticSCM",
    # --- .NET family → .NET ---
    "Microsoft .NET": ".NET",
    ".NET Framework": ".NET",
    ".NET Core": ".NET",
    ".NET 8": ".NET",
    ".NET MAUI": ".NET",
    ".NET Xaml": ".NET",
    "Visual Studio .NET": ".NET",
    "NET Core": ".NET",
    # --- ASP.NET family → ASP.NET ---
    "ASP.NET Core": "ASP.NET",
    "ASP.NET MVC": "ASP.NET",
    "ASP.NET Core MVC": "ASP.NET",
    "ASPX": "ASP.NET",
    # --- VB.NET → Visual Basic .NET ---
    "Visual Basic .NET": "VB.NET",
    # --- C/C++ typos ---
    "C/C+": "C/C++",
    # --- Agile family → Agile ---
    "Agile Scrum": "Agile",
    "Agile Development": "Agile",
    "Agile Methodology": "Agile",
    "Agile methodology": "Agile",
    "Agile methodologies": "Agile",
    "Agile Methodologies": "Agile",
    "Agile software development": "Agile",
    "Agile Kanban": "Agile",
    "Agile Project Management": "Agile",
    # --- AI family → Artificial Intelligence ---
    "AI/ML": "Artificial Intelligence",
    "AI/Machine Learning": "Artificial Intelligence",
    "AI Tools": "Artificial Intelligence",
    # --- ML → Machine Learning ---
    "ML": "Machine Learning",
    "Machine Learning Frameworks": "Machine Learning",
    "Machine Learning Lifecycle": "Machine Learning",
    # --- OOP → Object-Oriented Programming ---
    "OOP": "Object-Oriented Programming",
    "Object-Oriented Programming (OOP)": "Object-Oriented Programming",
    # --- REST extras ---
    "RESTful Web Services": "REST",
    # --- DevSecOps → DevOps ---
    "DevSecOps": "DevOps",
    # --- C + C++ → C/C++ ---
    "C": "C/C++",
    "C++": "C/C++",
    "C++ Programming": "C/C++",
    "C Language": "C/C++",
    "C Programming": "C/C++",
    # --- Python version variants ---
    "Python 3": "Python",
    "Python 2": "Python",
}

# Skills to remove — too vague/generic to be useful
VAGUE_SKILLS: set[str] = {
    "API", "APIs", "SDK", "IDE", "CLI", "GUI",
    "Programming", "Programming Languages", "Scripting", "Scripting Languages",
    "Coding", "Development", "Engineering", "Technology", "Tools",
    "Frameworks", "Libraries", "Platform", "Platforms", "Languages",
    "Software", "Hardware", "Testing", "Security", "Database", "Databases",
    "Cloud", "Web", "Mobile", "Data", "Analytics", "Reporting", "Monitoring",
    "Automation", "Deployment", "Logging", "Orchestration", "Containers", "Servers",
    "Networking", "Robotics", "Firmware", "Firmware Development", "Electronics",
    "Schematics", "Middleware", "Drivers", "Multimedia",
    "Compiler", "Compilers", "Debugger", "Debug",
    "Cloud Platforms", "Cloud Services", "Cloud Development",
    "Web Development", "Web Services", "Web Frameworks", "Web",
    "Mobile Development", "Mobile",
    "Software Development", "Software Engineering", "Software Design",
    "Software Architecture", "Software Testing",
    "Data Science", "Data Engineering", "Data Management", "Data Platform", "Data Lakes",
    "Data Structures and Algorithms",
    "Frontend Development", "Front-end Development", "Backend Development",
    "Full-stack Development", "Agile Development",
    "Embedded Systems", "Embedded Software", "Embedded Software Development",
    "Embedded Development", "Embedded Programming",
    "Hardware Design", "Hardware Systems",
    "Database Design", "Database Management", "Database Management Systems",
    "Relational Databases", "Relational Database", "Relational Database Management System",
    "NoSQL Databases", "Graph Databases", "Graph Database", "Vector Databases", "Vector Database",
    "Network Protocols", "Networking Protocols", "Communication Protocols",
    "Testing Frameworks", "Design Tools",
    "Software Development Best Practices", "Software Development Methodologies",
    "Software Quality Assurance", "QA Methodologies",
}


# Build case-insensitive index for fallback
_ALIASES_LOWER: dict[str, str] = {k.lower(): v for k, v in SKILL_ALIASES.items()}
_VAGUE_LOWER: set[str] = {s.lower() for s in VAGUE_SKILLS}


def normalize_skill(name: str) -> str:
    """Map a skill name to its canonical form.

    Checks exact match first, then case-insensitive match.
    Returns the original name if no alias is found.
    Returns empty string for vague/generic terms that should be removed.
    """
    name = name.strip()
    if name in VAGUE_SKILLS or name.lower() in _VAGUE_LOWER:
        return ""
    if name in SKILL_ALIASES:
        return SKILL_ALIASES[name]
    lower = name.lower()
    if lower in _ALIASES_LOWER:
        return _ALIASES_LOWER[lower]
    return name

